### ISSUE TITLE
Status of incorporation into pcap

### ISSUE THREAD

**Issue by versine** [eriknl/LoRaTap#1]
What is the current status on the request for a pcap link number? I noticed you sent a email to the mailing list three weeks ago, and was wondering if anything had changed since then

**Comment by eriknl** [comment]
I'm sorry but I haven't heard anything about it yet. It's also not listed on http://www.tcpdump.org/linktypes.html at the moment so I'm guessing it's still under review.

The released version won't change so if you're looking to use it for something that's fine. The reason I've requested the link-layer type number is so that support for dissection can be included in Wireshark. And then further dissectors can be added for LoRaWAN or custom protocols.

**Comment by versine** [comment]
Yeah, dissecting LoRaWAN is exactly the use case I'm interested in. Hopefully it will be approved soon.

**Comment by eriknl** [comment]
Good news! A DLT has been assigned so I'll get working on adding LoRaTap support to Wireshark. From there further subdissectors can be added like LoRaWAN.
